[build]
nixpacks = true

[build.nixpacksPlan]
phases.setup = { nixPkgs = ["dotnet-sdk_8"] }
phases.install.cmds = ["dotnet restore InvoiceApi.csproj"]
phases.build.cmds = ["dotnet publish InvoiceApi.csproj -c Release -o out"]
phases.start.cmd = "dotnet out/InvoiceApi.dll"
